"""Integration tests for AI enrichment in scan-all pipeline (Epic 25, Story 25.3).

Tests the end-to-end flow: scan-all --ai generates structural READMEs
then enriches non-leaf directories with AI-generated blockquote descriptions.
"""

from pathlib import Path

from codeindex.enricher import (
    build_enrich_prompt,
    extract_symbol_summary,
    inject_blockquote,
    should_enrich,
)


class TestEnrichmentIntegration:
    """Test the enrichment flow as it would work in scan-all --ai."""

    def test_full_enrich_flow(self, tmp_path):
        """Simulate: structural generation → AI enrich → parent reads description."""
        # Step 1: Simulate structural README_AI.md (as SmartWriter would generate)
        module_dir = tmp_path / "Vip"
        module_dir.mkdir()
        readme = module_dir / "README_AI.md"
        readme.write_text(
            "<!-- Generated by codeindex (navigation) at 2026-03-12 -->\n"
            "\n"
            "# Vip\n"
            "\n"
            "## Overview\n"
            "- **Files**: 48\n"
            "- **Symbols**: 386\n"
            "\n"
            "## Subdirectories\n"
            "- **Controller/** - 12 files\n"
        )

        # Step 2: Simulate AI enrichment (inject blockquote)
        inject_blockquote(readme, "会员等级管理、积分兑换、权益卡券")

        # Step 3: Verify parent can read the description
        from codeindex.writers.utils import extract_module_description

        desc = extract_module_description(module_dir)
        assert desc == "会员等级管理、积分兑换、权益卡券"

        # Step 4: Verify structural content is preserved
        content = readme.read_text()
        assert "## Overview" in content
        assert "**Files**: 48" in content
        assert "## Subdirectories" in content

    def test_enrich_only_non_leaf_directories(self):
        """Enrichment should only apply to overview and navigation levels."""
        assert should_enrich("overview") is True
        assert should_enrich("navigation") is True
        assert should_enrich("detailed") is False

    def test_enrich_prompt_from_parse_results(self):
        """Full flow: ParseResult → symbol summary → prompt."""
        from codeindex.parser import ParseResult, Symbol

        results = [
            ParseResult(
                path=Path("Pay.php"),
                symbols=[
                    Symbol(name="Pay", kind="class", signature="class Pay", line_start=1),
                    Symbol(
                        name="placeOrder", kind="method",
                        signature="public function placeOrder()", line_start=10,
                    ),
                ],
                imports=[],
            ),
        ]

        summary = extract_symbol_summary(results)
        prompt = build_enrich_prompt("Pay", summary)

        assert "Pay" in prompt
        assert "placeOrder" in prompt
        # Prompt should ask for brief description
        assert "20" in prompt or "brief" in prompt.lower()

    def test_re_enrich_updates_description(self, tmp_path):
        """Running enrich twice should update, not duplicate."""
        readme = tmp_path / "README_AI.md"
        readme.write_text("# Mod\n> 旧描述\n\n## Overview\n")

        inject_blockquote(readme, "新描述")
        content = readme.read_text()

        assert content.count(">") == 1
        assert "> 新描述" in content
        assert "旧描述" not in content
