"""Tests for enriched overview/navigation README generation.

Tests for Story: Enrich Overview/Navigation Level README_AI.md
- T1: Recursive statistics aggregation
- T2: Smart module description extraction
- T3: Top symbols summary collection
"""

import tempfile
from pathlib import Path

from codeindex.config import IndexingConfig
from codeindex.smart_writer import SmartWriter

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_child_readme(child_dir: Path, files: int, symbols: int, classes: list[str] | None = None) -> None:
    """Create a child README_AI.md with structured content matching codeindex output format."""
    child_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "<!-- Generated by codeindex (detailed) -->",
        "",
        f"# {child_dir.name}",
        "",
        "## Overview",
        "",
        f"- **Files**: {files}",
        f"- **Symbols**: {symbols}",
        "",
    ]
    if classes:
        lines.extend(["## Symbols", ""])
        for cls in classes:
            lines.append(f"- **class** `class {cls}`")
        lines.append("")
    (child_dir / "README_AI.md").write_text("\n".join(lines))


def _make_writer() -> SmartWriter:
    return SmartWriter(IndexingConfig())


# ---------------------------------------------------------------------------
# T1: Recursive Statistics Aggregation
# ---------------------------------------------------------------------------

class TestRecursiveStats:
    """Tests for _collect_recursive_stats()."""

    def test_aggregates_from_child_readmes(self):
        """3 child dirs with README_AI.md → aggregated totals."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "auth", files=10, symbols=45)
            _make_child_readme(root / "models", files=20, symbols=130)
            _make_child_readme(root / "utils", files=5, symbols=25)

            stats = writer._collect_recursive_stats(
                [root / "auth", root / "models", root / "utils"]
            )
            assert stats["files"] == 35
            assert stats["symbols"] == 200

    def test_handles_missing_readmes(self):
        """Some child dirs without README_AI.md → partial totals."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "auth", files=10, symbols=45)
            (root / "empty_mod").mkdir()  # No README_AI.md

            stats = writer._collect_recursive_stats(
                [root / "auth", root / "empty_mod"]
            )
            assert stats["files"] == 10
            assert stats["symbols"] == 45

    def test_overview_shows_aggregated_stats(self):
        """Overview output should show aggregated file/symbol counts."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "auth", files=42, symbols=313)
            _make_child_readme(root / "pay", files=17, symbols=89)

            result = writer.write_readme(
                dir_path=root,
                parse_results=[],
                level="overview",
                child_dirs=[root / "auth", root / "pay"],
            )
            content = result.path.read_text()
            # Should show aggregated totals, not 0
            assert "59" in content  # 42 + 17 files
            assert "402" in content  # 313 + 89 symbols

    def test_navigation_shows_aggregated_stats(self):
        """Navigation output should show aggregated file/symbol counts."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "sub1", files=10, symbols=50)
            _make_child_readme(root / "sub2", files=20, symbols=100)

            result = writer.write_readme(
                dir_path=root,
                parse_results=[],
                level="navigation",
                child_dirs=[root / "sub1", root / "sub2"],
            )
            content = result.path.read_text()
            # Should show aggregated totals
            assert "30" in content  # 10 + 20 files
            assert "150" in content  # 50 + 100 symbols


# ---------------------------------------------------------------------------
# T2: Smart Module Description
# ---------------------------------------------------------------------------

class TestSmartModuleDescription:
    """Tests for improved _extract_module_description()."""

    def test_extracts_structured_description(self):
        """Child README with files/symbols/classes → structured description."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(
                root / "cashier",
                files=42, symbols=313,
                classes=["Config", "Door", "FacePay", "Goods", "Login", "Order", "Refund"],
            )

            desc = writer._extract_module_description(root / "cashier")
            assert "42" in desc  # files count
            assert "313" in desc  # symbols count
            assert "Config" in desc  # class names
            assert "Module directory" not in desc

    def test_extracts_without_classes(self):
        """Child README with files/symbols but no classes → partial description."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "utils", files=5, symbols=25)

            desc = writer._extract_module_description(root / "utils")
            assert "5" in desc  # files count
            assert "25" in desc  # symbols count
            assert "Module directory" not in desc

    def test_fallback_when_no_readme(self):
        """No README_AI.md → returns 'Module directory'."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "empty").mkdir()

            desc = writer._extract_module_description(root / "empty")
            assert desc == "Module directory"

    def test_class_names_truncated_after_five(self):
        """More than 5 classes → show first 5 + count of remaining."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(
                root / "cashier",
                files=42, symbols=313,
                classes=["Config", "Door", "FacePay", "Goods", "Login",
                         "Order", "Refund", "Stock"],
            )

            desc = writer._extract_module_description(root / "cashier")
            # First 5 should be present
            assert "Config" in desc
            assert "Login" in desc
            # 6th+ should be summarized
            assert "+3" in desc  # 8 - 5 = 3 more


# ---------------------------------------------------------------------------
# T3: Top Symbols Summary
# ---------------------------------------------------------------------------

class TestTopSymbolsSummary:
    """Tests for _collect_top_symbols() and Key Components section."""

    def test_collects_symbols_from_children(self):
        """Multiple child READMEs → collects class symbols with module attribution."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "auth", files=5, symbols=20, classes=["Token", "Auth"])
            _make_child_readme(root / "pay", files=3, symbols=15, classes=["AliPay", "WxPay"])

            symbols = writer._collect_top_symbols([root / "auth", root / "pay"])
            names = [s[0] for s in symbols]
            assert "Token" in names
            assert "AliPay" in names
            # Each symbol should have (name, kind, module) tuple
            for sym in symbols:
                assert len(sym) == 3
                assert sym[1] in ("class", "function")

    def test_deduplicates_symbols(self):
        """Same class name in multiple modules → appears only once."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "mod1", files=5, symbols=20, classes=["Config", "Base"])
            _make_child_readme(root / "mod2", files=3, symbols=10, classes=["Config", "Helper"])

            symbols = writer._collect_top_symbols([root / "mod1", root / "mod2"])
            names = [s[0] for s in symbols]
            assert names.count("Config") == 1  # deduplicated

    def test_respects_limit(self):
        """Should cap at specified limit."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            many_classes = [f"Class{i}" for i in range(30)]
            _make_child_readme(root / "big", files=30, symbols=200, classes=many_classes)

            symbols = writer._collect_top_symbols([root / "big"], limit=10)
            assert len(symbols) <= 10

    def test_overview_contains_key_components_table(self):
        """Overview output should contain a Key Components table."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "auth", files=5, symbols=20, classes=["Token", "Auth"])
            _make_child_readme(root / "pay", files=3, symbols=15, classes=["AliPay"])

            result = writer.write_readme(
                dir_path=root,
                parse_results=[],
                level="overview",
                child_dirs=[root / "auth", root / "pay"],
            )
            content = result.path.read_text()
            assert "Key Components" in content
            assert "Token" in content
            assert "AliPay" in content
            # Table header
            assert "Symbol" in content
            assert "Type" in content
            assert "Module" in content

    def test_overview_no_key_components_when_no_symbols(self):
        """Overview without any class symbols → no Key Components section."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "empty", files=2, symbols=0)

            result = writer.write_readme(
                dir_path=root,
                parse_results=[],
                level="overview",
                child_dirs=[root / "empty"],
            )
            content = result.path.read_text()
            assert "Key Components" not in content


# ---------------------------------------------------------------------------
# T4: 2-Level Directory Tree in Overview
# ---------------------------------------------------------------------------

class TestTwoLevelTree:
    """Tests for 2-level directory tree display in overview."""

    def test_shows_grandchild_directories(self):
        """Overview tree should show subdirectories of each child module."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            # Application/ has 3 subdirs with README_AI.md
            _make_child_readme(root / "Application" / "Admin", files=10, symbols=50)
            _make_child_readme(root / "Application" / "Cashier", files=20, symbols=100)
            _make_child_readme(root / "Application" / "Token", files=3, symbols=15)
            # Application/ itself needs a README too
            _make_child_readme(root / "Application", files=33, symbols=165)

            result = writer.write_readme(
                dir_path=root,
                parse_results=[],
                level="overview",
                child_dirs=[root / "Application"],
            )
            content = result.path.read_text()
            # Grandchildren should appear in tree
            assert "Admin" in content
            assert "Cashier" in content
            assert "Token" in content

    def test_tree_shows_two_levels_structure(self):
        """Tree should have proper 2-level indentation."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "src" / "core", files=5, symbols=20)
            _make_child_readme(root / "src" / "utils", files=3, symbols=10)
            _make_child_readme(root / "src", files=8, symbols=30)
            _make_child_readme(root / "tests", files=4, symbols=12)

            result = writer.write_readme(
                dir_path=root,
                parse_results=[],
                level="overview",
                child_dirs=[root / "src", root / "tests"],
            )
            content = result.path.read_text()
            # Level 1 dirs should be present
            assert "src/" in content
            assert "tests/" in content
            # Level 2 dirs (under src/) should be present
            assert "core" in content
            assert "utils" in content

    def test_no_grandchildren_when_none_exist(self):
        """Leaf child with no subdirs → no extra indentation."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            _make_child_readme(root / "simple", files=5, symbols=20)

            result = writer.write_readme(
                dir_path=root,
                parse_results=[],
                level="overview",
                child_dirs=[root / "simple"],
            )
            content = result.path.read_text()
            assert "simple/" in content
            # Should not have any nested tree lines (│)
            tree_section = content.split("```")[1] if "```" in content else ""
            assert "│" not in tree_section

    def test_many_grandchildren_are_capped(self):
        """Child with 30+ subdirs → show first N + summary."""
        writer = _make_writer()
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            app = root / "Application"
            # Create 30 subdirectories with READMEs
            for i in range(30):
                _make_child_readme(app / f"Module{i:02d}", files=5, symbols=10)
            _make_child_readme(app, files=150, symbols=300)

            result = writer.write_readme(
                dir_path=root,
                parse_results=[],
                level="overview",
                child_dirs=[root / "Application"],
            )
            content = result.path.read_text()
            # Should show some modules but not all 30
            assert "Module00" in content
            # Should indicate there are more
            assert "more" in content.lower() or "..." in content
