"""Integration tests for AI enrichment in scan-all pipeline (Epic 25, Story 25.3).

Tests the end-to-end flow: scan-all --ai generates structural READMEs
then enriches non-leaf directories with AI-generated blockquote descriptions.
"""

from pathlib import Path

from codeindex.enricher import (
    build_enrich_prompt,
    extract_symbol_summary,
    inject_blockquote,
    should_enrich,
)


class TestEnrichmentIntegration:
    """Test the enrichment flow as it would work in scan-all --ai."""

    def test_full_enrich_flow(self, tmp_path):
        """Simulate: structural generation → AI enrich → parent reads description."""
        # Step 1: Simulate structural README_AI.md (as SmartWriter would generate)
        module_dir = tmp_path / "Vip"
        module_dir.mkdir()
        readme = module_dir / "README_AI.md"
        readme.write_text(
            "<!-- Generated by codeindex (navigation) at 2026-03-12 -->\n"
            "\n"
            "# Vip\n"
            "\n"
            "## Overview\n"
            "- **Files**: 48\n"
            "- **Symbols**: 386\n"
            "\n"
            "## Subdirectories\n"
            "- **Controller/** - 12 files\n"
        )

        # Step 2: Simulate AI enrichment (inject blockquote)
        inject_blockquote(readme, "会员等级管理、积分兑换、权益卡券")

        # Step 3: Verify parent can read the description
        from codeindex.writers.utils import extract_module_description

        desc = extract_module_description(module_dir)
        assert desc == "会员等级管理、积分兑换、权益卡券"

        # Step 4: Verify structural content is preserved
        content = readme.read_text()
        assert "## Overview" in content
        assert "**Files**: 48" in content
        assert "## Subdirectories" in content

    def test_enrich_only_non_leaf_directories(self):
        """Enrichment should only apply to overview and navigation levels."""
        assert should_enrich("overview") is True
        assert should_enrich("navigation") is True
        assert should_enrich("detailed") is False

    def test_enrich_prompt_from_parse_results(self):
        """Full flow: ParseResult → symbol summary → prompt."""
        from codeindex.parser import ParseResult, Symbol

        results = [
            ParseResult(
                path=Path("Pay.php"),
                symbols=[
                    Symbol(name="Pay", kind="class", signature="class Pay", line_start=1),
                    Symbol(
                        name="placeOrder", kind="method",
                        signature="public function placeOrder()", line_start=10,
                    ),
                ],
                imports=[],
            ),
        ]

        summary = extract_symbol_summary(results)
        prompt = build_enrich_prompt("Pay", summary)

        assert "Pay" in prompt
        assert "placeOrder" in prompt
        # Prompt should ask for concise description
        assert "30" in prompt or "concise" in prompt.lower()

    def test_build_enrich_summary_includes_own_symbols_for_leaf_dir(self, tmp_path):
        """GH #94: a leaf dir whose only child is __tests__ must still get its
        OWN file/symbol names into the enrichment summary — not just the
        useless 'Subdirectories: __tests__' that previously short-circuited it.
        """
        from codeindex.cli_scan import _build_enrich_summary
        from codeindex.config import Config

        controllers = tmp_path / "controllers"
        controllers.mkdir()
        (controllers / "user.py").write_text(
            "class UserController:\n"
            "    def login(self):\n"
            "        pass\n"
            "    def logout(self):\n"
            "        pass\n"
        )
        tests_dir = controllers / "__tests__"
        tests_dir.mkdir()
        (tests_dir / "user_test.py").write_text("def test_login():\n    pass\n")

        config = Config(languages=["python"], include=["**/*"], exclude=[])
        summary = _build_enrich_summary(controllers, [tests_dir], config)

        # Own files/symbols present (the bug: these were entirely absent)
        assert "user.py" in summary
        assert "login" in summary
        # Must NOT recurse into __tests__ (scan_directory recursive=False)
        assert "test_login" not in summary

    def test_re_enrich_updates_description(self, tmp_path):
        """Running enrich twice should update, not duplicate."""
        readme = tmp_path / "README_AI.md"
        readme.write_text("# Mod\n> 旧描述\n\n## Overview\n")

        inject_blockquote(readme, "新描述")
        content = readme.read_text()

        assert content.count(">") == 1
        assert "> 新描述" in content
        assert "旧描述" not in content
