"""Regression tests for GH #38: structural rewrites must preserve AI enrichment.

`scan-all --ai` Phase 2 injects an `<!-- enrichment: ok -->` marker plus a
`> description` blockquote. A later *structural-only* write (e.g. a post-commit
hook running `scan-all` without `--ai`, or Phase 1 of the next `--ai` run) used
to wipe both, so the idempotent cache went cold and the next `--ai` re-paid the
full N AI calls. SmartWriter.write_readme must now carry the two lines across a
rewrite when the prior file was successfully enriched.
"""

import tempfile
from pathlib import Path

from codeindex import enricher
from codeindex.config import IndexingConfig
from codeindex.smart_writer import SmartWriter


def _make_child_readme(child_dir: Path, files: int, symbols: int) -> None:
    """Minimal child README so an overview-level write produces real content."""
    child_dir.mkdir(parents=True, exist_ok=True)
    (child_dir / "README_AI.md").write_text(
        "\n".join(
            [
                "<!-- Generated by codeindex (detailed) -->",
                "",
                f"# {child_dir.name}",
                "",
                "## Overview",
                "",
                f"- **Files**: {files}",
                f"- **Symbols**: {symbols}",
                "",
            ]
        )
    )


def _write_structural(writer: SmartWriter, root: Path, children: list[Path]):
    return writer.write_readme(
        dir_path=root,
        parse_results=[],
        level="overview",
        child_dirs=children,
    )


class TestEnrichmentPreservedOnRewrite:
    def test_marker_and_blockquote_survive_structural_rewrite(self):
        """write structural → enrich → re-write structural → both lines present."""
        writer = SmartWriter(IndexingConfig())
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _make_child_readme(root / "auth", files=5, symbols=20)
            children = [root / "auth"]

            # Phase 1: structural write
            result = _write_structural(writer, root, children)
            readme = result.path

            # Phase 2: AI enrichment injects marker + blockquote
            desc = "会员认证与令牌管理"
            enricher.mark_enrichment_status(readme, "ok")
            enricher.inject_blockquote(readme, desc)
            assert enricher.has_successful_enrichment(readme)
            assert enricher.extract_blockquote_description(readme) == desc

            # Structural rewrite (e.g. post-commit hook, no --ai) must NOT wipe them
            _write_structural(writer, root, children)

            assert enricher.has_successful_enrichment(readme), "ok marker was wiped"
            assert enricher.extract_blockquote_description(readme) == desc, (
                "blockquote description was wiped"
            )

    def test_marker_only_survives_when_no_blockquote(self):
        """An ok marker with no blockquote is still preserved across rewrite."""
        writer = SmartWriter(IndexingConfig())
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _make_child_readme(root / "auth", files=5, symbols=20)
            children = [root / "auth"]

            readme = _write_structural(writer, root, children).path
            enricher.mark_enrichment_status(readme, "ok")

            _write_structural(writer, root, children)

            assert enricher.has_successful_enrichment(readme)

    def test_cache_stays_warm_across_repeated_rewrites(self):
        """Repro from the issue: third structural pass still shows ok marker,
        i.e. a subsequent `--ai` run would restore from cache (0 AI calls)."""
        writer = SmartWriter(IndexingConfig())
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _make_child_readme(root / "auth", files=5, symbols=20)
            children = [root / "auth"]

            readme = _write_structural(writer, root, children).path
            enricher.mark_enrichment_status(readme, "ok")
            enricher.inject_blockquote(readme, "认证模块")

            _write_structural(writer, root, children)  # intervening non-AI scan
            _write_structural(writer, root, children)  # and another

            assert enricher.has_successful_enrichment(readme)
            assert enricher.extract_blockquote_description(readme) == "认证模块"


class TestNoFabricatedEnrichment:
    def test_unenriched_readme_gets_no_marker_on_rewrite(self):
        """A README that was never enriched must not gain a marker from a rewrite."""
        writer = SmartWriter(IndexingConfig())
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _make_child_readme(root / "auth", files=5, symbols=20)
            children = [root / "auth"]

            readme = _write_structural(writer, root, children).path
            assert not enricher.has_successful_enrichment(readme)

            _write_structural(writer, root, children)
            assert not enricher.has_successful_enrichment(readme)

    def test_fresh_write_has_no_marker(self):
        """First-ever structural write of a new dir has no enrichment marker."""
        writer = SmartWriter(IndexingConfig())
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _make_child_readme(root / "auth", files=5, symbols=20)

            readme = _write_structural(writer, root, [root / "auth"]).path
            assert not enricher.has_successful_enrichment(readme)
