echo "$AFFECTED_DIRS" | while read -r dir; do
    [ -z "$dir" ] && continue

    README_PATH="$REPO_ROOT/$dir/README_AI.md"

    # Skip if no README_AI.md exists (not indexed yet)
    if [ ! -f "$README_PATH" ]; then
        echo "   ${YELLOW}⚠ $dir: not indexed (run 'codeindex scan $dir' first)${NC}"
        continue
    fi

    echo "\n${YELLOW}→ Updating ${dir}/README_AI.md${NC}"

    # Get diff for this directory
    DIR_DIFF=$(git diff HEAD~1 HEAD -- "$dir"/*.py 2>/dev/null || true)

    if [ -z "$DIR_DIFF" ]; then
        echo "   ${YELLOW}No Python diff found, skipping${NC}"
        continue
    fi

    # Read existing README_AI.md
    EXISTING_README=$(cat "$README_PATH" | grep -v '^<!-- Generated by codeindex' || cat "$README_PATH")

    # Create prompt for incremental update
    PROMPT="You are updating a README_AI.md file based on code changes.

CRITICAL INSTRUCTIONS:
1. Output ONLY valid markdown content
2. Start with \"# README_AI.md - <module_name>\"
3. Do NOT include any explanations or commentary
4. If changes are trivial, output the original content unchanged

## Commit Info
- Hash: ${COMMIT_HASH}
- Message: ${COMMIT_MSG}

## Code Diff
\`\`\`diff
${DIR_DIFF}
\`\`\`

## Current README_AI.md Content
${EXISTING_README}

## Your Task
Output the COMPLETE updated README_AI.md based on the diff.
"

    # Invoke AI CLI
    echo "   Invoking AI CLI..."

    AI_OUTPUT=$(python3 << PYEOF 2>/dev/null || true
import subprocess

prompt = '''${PROMPT//\'/\'\\\'\'}'''

try:
    result = subprocess.run(
        ['claude', '-p', prompt, '--allowedTools', 'Read'],
        capture_output=True,
        text=True,
        timeout=120
    )
    if result.returncode == 0 and result.stdout.strip():
        print(result.stdout)
except Exception:
    pass
PYEOF
)

    # Validate AI output
    VALID_OUTPUT=0
    if [ -n "$AI_OUTPUT" ]; then
        FIRST_LINE=$(echo "$AI_OUTPUT" | head -1 | xargs)
        if [[ "$FIRST_LINE" == \#* ]]; then
            VALID_OUTPUT=1
        elif echo "$AI_OUTPUT" | grep -q "^# "; then
            AI_OUTPUT=$(echo "$AI_OUTPUT" | sed -n '/^# /,$p')
            VALID_OUTPUT=1
        fi
    fi

    if [ $VALID_OUTPUT -eq 1 ] && [ ${#AI_OUTPUT} -gt 100 ]; then
        # Write valid AI output
        TIMESTAMP=$(date -Iseconds)
        {
            echo "<!-- Generated by codeindex at ${TIMESTAMP} -->"
            echo ""
            echo "$AI_OUTPUT"
        } > "$README_PATH"
        echo "   ${GREEN}✓ Updated via AI${NC}"
        echo "$README_PATH" >> /tmp/codeindex_updated_$$
    else
        # Fallback: append change summary
        echo "   ${YELLOW}AI unavailable, appending change summary${NC}"
        TIMESTAMP=$(date -Iseconds)

        CLEAN_README=$(cat "$README_PATH" | sed '/^---$/,/^## Recent Changes/d' | sed '/^## Recent Changes/,$d')

        {
            echo "$CLEAN_README"
            echo ""
            echo "---"
            echo ""
            echo "## Recent Changes"
            echo ""
            echo "**Commit \`${COMMIT_HASH}\`**: ${COMMIT_MSG}"
            echo ""
            echo "Changed files:"
            git diff-tree --no-commit-id --name-only -r HEAD -- "$dir"/*.py | while read f; do
                echo "- \`$(basename $f)\`"
            done
        } > "$README_PATH"
        echo "   ${GREEN}✓ Appended change summary${NC}"
        echo "$README_PATH" >> /tmp/codeindex_updated_$$
    fi
done

# Commit updated files
if [ -f /tmp/codeindex_updated_$$ ]; then
    UPDATED_COUNT=$(wc -l < /tmp/codeindex_updated_$$ | tr -d ' ')

    if [ "$UPDATED_COUNT" -gt 0 ]; then
        echo "\n${CYAN}→ Committing ${UPDATED_COUNT} updated README_AI.md file(s)...${NC}"

        cat /tmp/codeindex_updated_$$ | while read readme; do
            git add "$readme"
        done

        git commit --no-verify -m "docs: auto-update README_AI.md for ${COMMIT_HASH}

Updated by post-commit hook based on code changes.
Update level: ${LEVEL}

Co-Authored-By: Claude <noreply@anthropic.com>"

        echo "${GREEN}✓ README_AI.md updates committed${NC}"
    fi

    rm -f /tmp/codeindex_updated_$$
fi

