"""Navigation level README generator (module level)."""

from datetime import datetime
from pathlib import Path

from ..config import IndexingConfig
from ..parser import ParseResult
from .utils import extract_module_description, get_key_symbols, group_files


class NavigationGenerator:
    """Generates navigation-level README content for module directories."""

    def __init__(self, config: IndexingConfig):
        self.config = config

    def generate(
        self,
        dir_path: Path,
        parse_results: list[ParseResult],
        child_dirs: list[Path],
    ) -> str:
        """Generate navigation level README content."""
        from . import NAVIGATION_DISCLAIMER
        timestamp = datetime.now().isoformat()
        lines = [
            NAVIGATION_DISCLAIMER,
            f"<!-- Generated by codeindex (navigation) at {timestamp} -->",
            "",
            f"# {dir_path.name}",
            "",
        ]

        # Navigation level: cli_scan.py runs scan_directory with recursive=True,
        # so parse_results already covers this dir AND every descendant. Adding
        # child README stats on top would double-count — see GH #45.
        # (Overview level is different: that path scans non-recursively and DOES
        # need to aggregate child stats. See overview_generator.py.)
        total_files = len(parse_results)
        total_symbols = sum(len(r.symbols) for r in parse_results)

        lines.extend([
            "## Overview",
            "",
            f"- **Files**: {total_files}",
            f"- **Symbols**: {total_symbols}",
            f"- **Subdirectories**: {len(child_dirs)}",
            "",
        ])

        # Subdirectories (if any)
        if child_dirs:
            lines.extend([
                "## Subdirectories",
                "",
            ])
            for child in sorted(child_dirs):
                description = extract_module_description(child)
                lines.append(f"- **{child.name}/** - {description}")
            lines.extend(["", ""])

        # Grouped files — only this dir's direct children. Nav-level scans
        # are recursive (see the GH #45 stats note above), so parse_results
        # includes descendants. Surfacing them flat here loses path info and
        # misleads agents that try to Read `<this dir>/<flat-name>` → 404
        # (GH #76). Each subdir carries its own README_AI.md listing its own
        # files.
        direct_results = [r for r in parse_results if r.path.parent == dir_path]
        if direct_results:
            grouped = group_files(direct_results, self.config)
            lines.extend([
                "## Files",
                "",
            ])

            for group_name, group_results in grouped.items():
                if group_name != "_ungrouped":
                    group_desc = self.config.grouping.patterns.get(group_name, "")
                    lines.append(f"### {group_name} ({len(group_results)} files)")
                    if group_desc:
                        lines.append(f"_{group_desc}_")
                    lines.append("")

                for result in group_results:
                    if result.error:
                        continue
                    # List key classes/functions only
                    key_symbols = get_key_symbols(result.symbols)
                    symbol_summary = ", ".join(
                        s.name.split("::")[-1].split(".")[-1]
                        for s in key_symbols[:3]
                    )
                    if symbol_summary:
                        lines.append(f"- **{result.path.name}** - {symbol_summary}")
                    else:
                        lines.append(f"- {result.path.name}")

                lines.append("")

        return "\n".join(lines)
